CREATE TABLE IF NOT EXISTS `campi`( 
`id` INT(11) NOT NULL AUTO_INCREMENT, 
`nome` VARCHAR(255) NOT NULL, 
`cidade` VARCHAR(255) NOT NULL, 
`uf` VARCHAR(255) NOT NULL, 
PRIMARY KEY (`id`)) 
ENGINE = InnoDB;