CREATE TABLE IF NOT EXISTS `campi`(
`id` INT(11) NOT NULL AUTO_INCREMENT, 
`nome` VARCHAR(255) NOT NULL, 
`cidade` VARCHAR(255) NOT NULL,
`uf` VARCHAR(255) NOT NULL, 
PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `cursos`(
`id` INT(11) NOT NULL AUTO_INCREMENT, 
`id_depto` VARCHAR(255) NOT NULL, 
`nome` VARCHAR(255) NOT NULL, 
`horas_total` INT(11) NOT NULL, 
`modalidade` VARCHAR(255) NOT NULL, 
PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `turmas`(
`id` INT(11) NOT NULL AUTO_INCREMENT, 
`id_cursos` INT(11) NOT NULL, 
`nome` VARCHAR(255) NOT NULL, 
PRIMARY KEY (`id`)) ENGINE = InnoDB;
